# Ini didukung platform model pendanaan

github:  # Ganti dengan 4 GitHub Sponsor yang diaktifkan nama pengguna misalnya, [user1, user2]
patreon:  # Ganti dengan satu nama pengguna Patreon
open_collective:  # Ganti dengan satu nama pengguna Open Collective
ko_fi:  # Ganti dengan satu nama pengguna Ko-fi tunggal
tidelift:  # Ganti dengan satu nama platform Tidelift/nama paket-nama misalnya, npm/babel
community_bridge:  # Ganti dengan satu nama proyek Jembatan Community misalnya, cloud-foundry
liberapay:  # Ganti dengan satu nama pengguna Liberapay
issuehunt:  # Ganti dengan satu nama pengguna IssueHunt
otechie:  # Replace with a single Otechie username
lfx_crowdfunding:  # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
kebiasaan:  # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
